apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: thumbnail-generator
  labels:
    app: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: <your_ecr_url>/celery-worker:latest
          command: ["celery", "-A", "worker.worker.celery", "worker", "--loglevel=info"]
          envFrom:
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
