version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
  
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: flask-api
    ports:
      - "5001:5000"
    env_file:
      - .env
    volumes:
      - shared-tmp:/tmp  # 👈 Shared /tmp directory
    depends_on:
      - redis
  
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: celery-worker
    env_file:
      - .env
    volumes:
      - shared-tmp:/tmp  # 👈 Same shared /tmp
    depends_on:
      - redis

volumes:
  shared-tmp:  # 👈 Define the shared named volume
