apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: thumbnail-generator
  labels:
    app: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: 123456789012.dkr.ecr.us-east-2.amazonaws.com/flask-api:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
