apiVersion: v1
kind: Service
metadata:
  name: flask-api
  namespace: thumbnail-generator
  labels:
    app: flask-api
spec:
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
